version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:5000"
  pool:
    num_workers: 20
    supervisor:
      # watch_tick defines how often to check the state of the workers (seconds)
      watch_tick: 10s
      # ttl defines maximum time worker is allowed to live (seconds)
      ttl: 10s

logs:
  level: error